const host = "35.246.75.160:443";

export default {
  login: "login",
  register: "register",
  acceptRequest: "acceptRequest",
  sendRequest: "sendRequest",
  denyRequest: "denyRequest",
  listRequest: "listRequest",
  listFriends: "listFriends",
  deleteFriend: "deleteFriend",
  viewProfile: "viewProfile",
  changeName: "changeNameProfile",
  newGame: "newGame",
  listGames: "listGames",
  listInvites: "listInvite",
  inviteGame: "inviteGame",
  acceptInvite: "acceptInvite",
  denyInvite: "denyInvite",
  listPlayers: "listPlayers",
  listFriendsGame: "listFriendsGame",
  startGame: "startGame",
  addRespuesta: "addRespuesta",
  all: "all",
  img: "http://"+host+"/api/returnImageProfile/",
  turnImg: "http://"+host+"/api/returnImageResponse/",
  sendImg: "addImage",
  sendText: "addText",
  getTurn: "returnResponse",
  getHilos: "returnAllResponses",
  voteDibujante: "votarDibujo",
  voteListo: "votarListo",
  voteGracioso: "votarGracioso",
  verResultados: "puntosPartida",
  verPuntuacion: "puntosJugador",
  resetVotos: "resetVotos",
};
